version: "2"
services:
  python_libstorj:
    build:
      context: .
      dockerfile: ./dockerfiles/python_libstorj.dockerfile
    environment:
      STORJ_BRIDGE: http://bridge:6382
    links:
      - bridge
    volumes:
      - ./lib:/python_libstorj/lib
      - ./tests:/python_libstorj/tests
  bridge:
    build:
      context: .
      dockerfile: ./dockerfiles/bridge.dockerfile
      args:
        - STORJ_EMAIL
        - STORJ_PASS
        - STORJ_KEYPASS
        - STORJ_MNEMONIC
    environment:
      STORJ_BRIDGE: http://bridge:6382
      STORJ_KEYPASS:
    ports:
     - 6382:6382
    command: bash -c ". /root/.nvm/nvm.sh && ./scripts/start_everything.sh && /bin/sleep infinity"
